name: Publish VS Code Extension

on:
  push:
    branches:
      - develop
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: vsce

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g pnpm@latest-10
          npm install -g @vscode/vsce
          pnpm install

      - name: Read base version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Modify version based on branch
        id: set_version
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          BASE_VERSION="${{ steps.get_version.outputs.VERSION }}"
          RUN_NUMBER="${GITHUB_RUN_NUMBER}"
          
          MAJOR=$(echo "$BASE_VERSION" | cut -d. -f1)
          MINOR=$(echo "$BASE_VERSION" | cut -d. -f2)
          
          if [ "$BRANCH" = "develop" ]; then
            PATCH=$((RUN_NUMBER))
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
            echo "🔧 Pre-release version: $NEW_VERSION"
            jq ".version = \"$NEW_VERSION\"" package.json > tmp && mv tmp package.json
            echo "FINAL_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          elif [ "$BRANCH" = "main" ]; then
            PATCH=$((RUN_NUMBER + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
            echo "🚀 Release version: $NEW_VERSION"
            jq ".version = \"$NEW_VERSION\"" package.json > tmp && mv tmp package.json
            echo "FINAL_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Skipping branch: $BRANCH"
            exit 0
          fi

      - name: Package extension
        id: package_version
        run: |
          if [ "$BRANCH" = "develop" ]; then
            vsce package --pre-release
          else
            vsce package
          fi

      - name: Publish to VS Code Marketplace
        run: npx vsce publish -p ${{ secrets.TOKEN }}
